version: '3'

services:
  selenium-hub:
    image: selenium/hub
    # environment:
    #   - SE_OPTS="-debug"  # debugging
    # ports:
    #   - 4444:4444
    expose:
      - 4444
    networks:
      - boomerang
